### ISSUE TITLE
Status when no target is running

### ISSUE THREAD

**Issue by wilecoyote** [SMC242/CodingDND#14]
Hi, i love the idea of your plugin very much. For me there is only one issue. Every day before i close discord i set my status to invisible. With your plugin enabled my status is automatically set to online (if this is the setting within the plugin when none of the targets is running). I think it would be a smoother experience if the status wouldn't change when status is set to invisible. Overall, it would be better to set the active status to the last status before DND was activated,

**Comment by SMC242** [comment]
Summarizing to check that I understood:
- No targets are running and `inactive_status` = online
- You manually set invisible
- The plugin changes your status from invisible to online

Is that right?

**Comment by wilecoyote** [comment]
Yes, it is, I set my status to invisible and close discord before i shut down my pc. and go to bed. Next day when i start discord again the plugin sets me automatically to online.

**Comment by SMC242** [comment]
Okay. Thanks for explaining the issue. Here are some ideas for how I can fix this:

1. The plugin has 2 loops: 1 checks if a target is running and sets the inactive/active status. The other checks if the status has changed since it was last set.

I would add an option to disable this loop. 

#### What would this change about your story?
1. No targets are running
2. You set invisible
3. The plugin does not check if the status changed - the next time it can update the status is if a target is running

2. I add an extra status option: `previous status` as a value for `inactive_status`

#### What would this change about your story?
1. No targets are running
2. You set invisible
3. The plugin checks if targets are running. It sees there are none, so sets your status to invisible


Both of these solutions have a problem: they cannot fully solve your issue. This is because when you re-open Discord, the plugin's state will be lost. This means that it will re-check if targets are running, and set a status accordingly. I'll sleep on this and see if I can find a good solution. 

One option may be to save the last status when Discord is closed. I'm not sure how possible or reliable that would be. I'd have to check

**Comment by SMC242** [comment]
What do you think about those solutions?

**Comment by wilecoyote** [comment]
I don't know if it is technically possible, but my solution would be:

1. Check if status invisible is set. If it is set don't change it even if an IDE is started.
2. In every other case when the IDE is closed set it back to the last inactive status 

I know there are some plugins such as Notification Sounds which have extensive setting options. They must save their state somewhere. So maybe it would help to save the last status of your plugin in the same way and load it on discord start.

**Comment by SMC242** [comment]
That would be possible. My immediate question is: does this use case extend to other statuses than invisible?

**Comment by wilecoyote** [comment]
I do not think so. In my opinion, "invisible" should be the only status that shouldn't be changed in any case. If you are set to idle/away and start your IDE, your technically no longer idle. So, it is correct to set the DND status. If DND is already set, then there is nothing which must be changed. Maybe it would be an option to check the status of the Custom Status also but in no case do I want to overwhelm you with my ideas/wishes

**Comment by SMC242** [comment]
That makes sense. I'll work on the invisible thing when I get the time. No ETA on that as I'm busy at the moment.

As for integrating with `Custom Status`: it's a neat idea but sounds painful to do. Relying on another BD plugin author given the frequency that plugins break would likely cause bugs in my plugin that I could not fix. It could also mean constantly fixing my code to work with changes to their code. I'll make this one a very big *maybe*

**Comment by wilecoyote** [comment]
That was a mistake on my part. The "custom personal status" function is from Discord itself; the plugin only allows you to save presets. So, it is not necessary to take the plugin into account.

**Comment by SMC242** [comment]
Well I could re-implement their plugin and automate it like the standard 4 statuses. That's doable

**Comment by SMC242** [comment]
I've pushed an update including this feature :)

**Comment by wilecoyote** [comment]
> I've pushed an update including this feature :)

Hi, i've seen it but can't get into the settings menu.

**Comment by SMC242** [comment]
I expect this is due to a settings format change. Read the changelog or the announcement in my Discord server for instructions on how to fix it

I would rewrite the instructions but I'm using my phone rn ._.

**Comment by wilecoyote** [comment]
I have deleted the plugin and the settings json completely and downloaded/installed the latest version. I can open the settings but can't unfold the sections.

**Comment by SMC242** [comment]
oooh strange. Can you check the console for anything weird?

Also do you have ZeresPluginLib?
